### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Rilong** [Rilong/bloglaravel#1]
## Posts
- [ ] Create user
- [ ] Create post resource
- [ ] Create methods for post model
---
## Core
- [ ] Create relations for models
